'use strict';

module.exports = [
  {
    "CVE": "E3205",
    "CATEGORIA": "PREINCORPORACIÓN EDUCACION SUPERIOR FOR. “A”",
    "CAT_SIMPLE": "PREINCORPORACIÓN",
    "ORD_CAT": 0,
    "CT_AV": null
  },
  {
    "CVE": "E3206",
    "CATEGORIA": "PREINCORPORACIÓN EDUCACION SUPERIOR D.F. “A”",
    "CAT_SIMPLE": "PREINCORPORACIÓN",
    "ORD_CAT": 0,
    "CT_AV": null
  },
  {
    "CVE": "E3207",
    "CATEGORIA": "PREINCORPORACIÓN EDUCACION SUPERIOR FOR. “B”",
    "CAT_SIMPLE": "PREINCORPORACIÓN",
    "ORD_CAT": 0,
    "CT_AV": null
  },
  {
    "CVE": "E3208",
    "CATEGORIA": "PREINCORPORACIÓN EDUCACION SUPERIOR D.F. “B”",
    "CAT_SIMPLE": "PREINCORPORACIÓN",
    "ORD_CAT": 0,
    "CT_AV": null
  },
  {
    "CVE": "E3209",
    "CATEGORIA": "SUPERVISOR EDUCACION SUPERIOR FOR. T.C. “A”",
    "CAT_SIMPLE": "SUPERVISOR",
    "ORD_CAT": 0,
    "CT_AV": null
  },
  {
    "CVE": "E3210",
    "CATEGORIA": "SUPERVISOR EDUCACION SUPERIOR D.F. T.C. “A”",
    "CAT_SIMPLE": "SUPERVISOR",
    "ORD_CAT": 0,
    "CT_AV": null
  },
  {
    "CVE": "E3211",
    "CATEGORIA": "SUPERVISOR EDUCACION SUPERIORFOR. T.C. “B”",
    "CAT_SIMPLE": "SUPERVISOR",
    "ORD_CAT": 0,
    "CT_AV": null
  },
  {
    "CVE": "E3212",
    "CATEGORIA": "SUPERVISOR EDUCACION SUPERIOR D.F. T.C. “B”",
    "CAT_SIMPLE": "SUPERVISOR",
    "ORD_CAT": 0,
    "CT_AV": null
  },
  {
    "CVE": "E3302",
    "CATEGORIA": "PREFECTO D.F. T.C. “A”",
    "CAT_SIMPLE": "PREFECTO",
    "ORD_CAT": 0,
    "CT_AV": null
  },
  {
    "CVE": "E3304",
    "CATEGORIA": "PREFECTO D.F. T.C. “B”",
    "CAT_SIMPLE": "PREFECTO",
    "ORD_CAT": 0,
    "CT_AV": null
  },
  {
    "CVE": "E3306",
    "CATEGORIA": "PREFECTO D.F. T.C. “C”",
    "CAT_SIMPLE": "PREFECTO",
    "ORD_CAT": 0,
    "CT_AV": null
  },
  {
    "CVE": "E3109",
    "CATEGORIA": "TÉCNICO DOCENTE ASIGNATURA EDUCACION SUPERIOR FOR. “A”",
    "CAT_SIMPLE": "TÉCNICO DOCENTE ASIGNATURA",
    "ORD_CAT": 1100,
    "CT_AV": null
  },
  {
    "CVE": "E3110",
    "CATEGORIA": "TÉCNICO DOCENTE ASIGNATURA EDUCACION SUPERIOR D.F. “A”",
    "CAT_SIMPLE": "TÉCNICO DOCENTE ASIGNATURA",
    "ORD_CAT": 1100,
    "CT_AV": null
  },
  {
    "CVE": "E3111",
    "CATEGORIA": "TÉCNICO DOCENTE ASIGNATURA EDUCACION SUPERIOR FOR. “B”",
    "CAT_SIMPLE": "TÉCNICO DOCENTE ASIGNATURA",
    "ORD_CAT": 1100,
    "CT_AV": null
  },
  {
    "CVE": "E3112",
    "CATEGORIA": "TÉCNICO DOCENTE ASIGNATURA EDUCACION SUPERIOR D.F.. “B”",
    "CAT_SIMPLE": "TÉCNICO DOCENTE ASIGNATURA",
    "ORD_CAT": 1100,
    "CT_AV": null
  },
  {
    "CVE": "E3113",
    "CATEGORIA": "TÉCNICO DOCENTE ASIGNATURA EDUCACION SUPERIOR FOR. “C”",
    "CAT_SIMPLE": "TÉCNICO DOCENTE ASIGNATURA",
    "ORD_CAT": 1100,
    "CT_AV": null
  },
  {
    "CVE": "E3114",
    "CATEGORIA": "TÉCNICO DOCENTE ASIGNATURA EDUCACION SUPERIOR D.F. “C”",
    "CAT_SIMPLE": "TÉCNICO DOCENTE ASIGNATURA",
    "ORD_CAT": 1100,
    "CT_AV": null
  },
  {
    "CVE": "E3123",
    "CATEGORIA": "TÉCNICO DOCENTE ASIGNATURA EDUCACION MEDIA SUPERIOR FOR. “A”",
    "CAT_SIMPLE": "TÉCNICO DOCENTE ASIGNATURA",
    "ORD_CAT": 1100,
    "CT_AV": null
  },
  {
    "CVE": "E3124",
    "CATEGORIA": "TÉCNICO DOCENTE ASIGNATURA EDUCACION MEDIA SUPERIOR D.F. “A”",
    "CAT_SIMPLE": "TÉCNICO DOCENTE ASIGNATURA",
    "ORD_CAT": 1100,
    "CT_AV": null
  },
  {
    "CVE": "E3125",
    "CATEGORIA": "TÉCNICO DOCENTE ASIGNATURA EDUCACION MEDIA SUPERIOR FOR. “B”",
    "CAT_SIMPLE": "TÉCNICO DOCENTE ASIGNATURA",
    "ORD_CAT": 1100,
    "CT_AV": null
  },
  {
    "CVE": "E3126",
    "CATEGORIA": "TÉCNICO DOCENTE ASIGNATURA EDUCACION MEDIA SUPERIOR D.F.. “B”",
    "CAT_SIMPLE": "TÉCNICO DOCENTE ASIGNATURA",
    "ORD_CAT": 1100,
    "CT_AV": null
  },
  {
    "CVE": "E3128",
    "CATEGORIA": "TÉCNICO DOCENTE ASIGNATURA EDUCACION MEDIA SUPERIOR D.F. “C”",
    "CAT_SIMPLE": "TÉCNICO DOCENTE ASIGNATURA",
    "ORD_CAT": 1100,
    "CT_AV": null
  },
  {
    "CVE": "E3137",
    "CATEGORIA": "TÉCNICO DOCENTE ASIGNATURA EDUCACION MEDIA SUPERIOR FOR. “C”",
    "CAT_SIMPLE": "TÉCNICO DOCENTE ASIGNATURA",
    "ORD_CAT": 1100,
    "CT_AV": null
  },
  {
    "CVE": "E6006",
    "CATEGORIA": "TECNICO DOCENTE DE ASIGNATURA \"A\" (EDUCACION SUPERIOR)",
    "CAT_SIMPLE": "TÉCNICO DOCENTE ASIGNATURA",
    "ORD_CAT": 1100,
    "CT_AV": null
  },
  {
    "CVE": "E6008",
    "CATEGORIA": "TECNICO DOCENTE DE ASIGNATURA \"B\" (EDUCACION SUPERIOR)",
    "CAT_SIMPLE": "TÉCNICO DOCENTE ASIGNATURA",
    "ORD_CAT": 1100,
    "CT_AV": null
  },
  {
    "CVE": "E6010",
    "CATEGORIA": "TECNICO DOCENTE DE ASIGNATURA \"C\" (EDUCACION SUPERIOR)",
    "CAT_SIMPLE": "TÉCNICO DOCENTE ASIGNATURA",
    "ORD_CAT": 1100,
    "CT_AV": null
  },
  {
    "CVE": "E6012",
    "CATEGORIA": "TECNICO DOCENTE DE ASIGNATURA \"A\" (EDUCACION MEDIA SUPERIOR)",
    "CAT_SIMPLE": "TÉCNICO DOCENTE ASIGNATURA",
    "ORD_CAT": 1100,
    "CT_AV": null
  },
  {
    "CVE": "E6014",
    "CATEGORIA": "TECNICO DOCENTE DE ASIGNATURA \"B\" (EDUCACION MEDIA SUPERIOR)",
    "CAT_SIMPLE": "TÉCNICO DOCENTE ASIGNATURA",
    "ORD_CAT": 1100,
    "CT_AV": null
  },
  {
    "CVE": "E2831",
    "CATEGORIA": "TÉCNICO DOCENTE AUXILIAR EDUCACION SUPERIOR FOR.  ½ T. “A” ",
    "CAT_SIMPLE": "TÉCNICO DOCENTE AUXILIAR",
    "ORD_CAT": 1200,
    "CT_AV": null
  },
  {
    "CVE": "E2832",
    "CATEGORIA": "TÉCNICO DOCENTE AUXILIAR EDUCACION SUPERIOR D.F. ½ T. “A”",
    "CAT_SIMPLE": "TÉCNICO DOCENTE AUXILIAR",
    "ORD_CAT": 1200,
    "CT_AV": null
  },
  {
    "CVE": "E2833",
    "CATEGORIA": "TÉCNICO DOCENTE AUXILIAR EDUCACION SUPERIOR FOR.  ½ T. “B” ",
    "CAT_SIMPLE": "TÉCNICO DOCENTE AUXILIAR",
    "ORD_CAT": 1200,
    "CT_AV": null
  },
  {
    "CVE": "E2834",
    "CATEGORIA": "TÉCNICO DOCENTE AUXILIAR EDUCACION SUPERIOR D.F. ½ T. “B”",
    "CAT_SIMPLE": "TÉCNICO DOCENTE AUXILIAR",
    "ORD_CAT": 1200,
    "CT_AV": null
  },
  {
    "CVE": "E2835",
    "CATEGORIA": "TÉCNICO DOCENTE AUXILIAR EDUCACION SUPERIOR FOR.  ½ T. “C” ",
    "CAT_SIMPLE": "TÉCNICO DOCENTE AUXILIAR",
    "ORD_CAT": 1200,
    "CT_AV": null
  },
  {
    "CVE": "E2836",
    "CATEGORIA": "TÉCNICO DOCENTE AUXILIAR EDUCACION SUPERIOR D.F. ½ T. “C”",
    "CAT_SIMPLE": "TÉCNICO DOCENTE AUXILIAR",
    "ORD_CAT": 1200,
    "CT_AV": null
  },
  {
    "CVE": "E2847",
    "CATEGORIA": "TÉCNICO DOCENTE AUXILIAR EDUCACION MEDIA SUPERIOR FOR.  ½ T. “A” ",
    "CAT_SIMPLE": "TÉCNICO DOCENTE AUXILIAR",
    "ORD_CAT": 1200,
    "CT_AV": null
  },
  {
    "CVE": "E2848",
    "CATEGORIA": "TÉCNICO DOCENTE AUXILIAR EDUCACION MEDIA SUPERIOR D.F. ½ T. “A”",
    "CAT_SIMPLE": "TÉCNICO DOCENTE AUXILIAR",
    "ORD_CAT": 1200,
    "CT_AV": null
  },
  {
    "CVE": "E2849",
    "CATEGORIA": "TÉCNICO DOCENTE AUXILIAR EDUCACION MEDIA SUPERIOR FOR.  ½ T. “B” ",
    "CAT_SIMPLE": "TÉCNICO DOCENTE AUXILIAR",
    "ORD_CAT": 1200,
    "CT_AV": null
  },
  {
    "CVE": "E2850",
    "CATEGORIA": "TÉCNICO DOCENTE AUXILIAR EDUCACION MEDIA SUPERIOR D.F. ½ T. “B”",
    "CAT_SIMPLE": "TÉCNICO DOCENTE AUXILIAR",
    "ORD_CAT": 1200,
    "CT_AV": null
  },
  {
    "CVE": "E2851",
    "CATEGORIA": "TÉCNICO DOCENTE AUXILIAR EDUCACION MEDIA SUPERIOR FOR.  ½ T. “C” ",
    "CAT_SIMPLE": "TÉCNICO DOCENTE AUXILIAR",
    "ORD_CAT": 1200,
    "CT_AV": null
  },
  {
    "CVE": "E2852",
    "CATEGORIA": "TÉCNICO DOCENTE AUXILIAR EDUCACION MEDIA SUPERIOR D.F. ½ T. “C”",
    "CAT_SIMPLE": "TÉCNICO DOCENTE AUXILIAR",
    "ORD_CAT": 1200,
    "CT_AV": null
  },
  {
    "CVE": "E2931",
    "CATEGORIA": "TÉCNICO DOCENTE AUXILIAR  EDUCACION SUPERIOR FOR. ¾ T. “A”",
    "CAT_SIMPLE": "TÉCNICO DOCENTE AUXILIAR",
    "ORD_CAT": 1200,
    "CT_AV": null
  },
  {
    "CVE": "E2932",
    "CATEGORIA": "TÉCNICO DOCENTE AUXILIAR EDUCACION SUPERIOR D.F. ¾ T. “A”",
    "CAT_SIMPLE": "TÉCNICO DOCENTE AUXILIAR",
    "ORD_CAT": 1200,
    "CT_AV": null
  },
  {
    "CVE": "E2933",
    "CATEGORIA": "TÉCNICO DOCENTE AUXILIAR EDUCACION SUPERIOR FOR. ¾ T. “B”",
    "CAT_SIMPLE": "TÉCNICO DOCENTE AUXILIAR",
    "ORD_CAT": 1200,
    "CT_AV": null
  },
  {
    "CVE": "E2934",
    "CATEGORIA": "TÉCNICO DOCENTE AUXILIAR EDUCACION SUPERIOR D.F. ¾ T. “B”",
    "CAT_SIMPLE": "TÉCNICO DOCENTE AUXILIAR",
    "ORD_CAT": 1200,
    "CT_AV": null
  },
  {
    "CVE": "E2935",
    "CATEGORIA": "TÉCNICO DOCENTE AUXILIAR EDUCACION SUPERIOR FOR. ¾ T. “C”",
    "CAT_SIMPLE": "TÉCNICO DOCENTE AUXILIAR",
    "ORD_CAT": 1200,
    "CT_AV": null
  },
  {
    "CVE": "E2936",
    "CATEGORIA": "TÉCNICO DOCENTE AUXILIAR EDUCACION SUPERIOR D.F. ¾ T. “C”",
    "CAT_SIMPLE": "TÉCNICO DOCENTE AUXILIAR",
    "ORD_CAT": 1200,
    "CT_AV": null
  },
  {
    "CVE": "E2947",
    "CATEGORIA": "TÉCNICO DOCENTE AUXILIAR EDUCACION MEDIA SUPERIOR FOR.  ¾ T. “A” ",
    "CAT_SIMPLE": "TÉCNICO DOCENTE AUXILIAR",
    "ORD_CAT": 1200,
    "CT_AV": null
  },
  {
    "CVE": "E2948",
    "CATEGORIA": "TÉCNICO DOCENTE AUXILIAR EDUCACION MEDIA SUPERIOR D.F. ¾ T. “A”",
    "CAT_SIMPLE": "TÉCNICO DOCENTE AUXILIAR",
    "ORD_CAT": 1200,
    "CT_AV": null
  },
  {
    "CVE": "E2949",
    "CATEGORIA": "TÉCNICO DOCENTE AUXILIAR EDUCACION MEDIA SUPERIOR FOR. ¾ T. “B”",
    "CAT_SIMPLE": "TÉCNICO DOCENTE AUXILIAR",
    "ORD_CAT": 1200,
    "CT_AV": null
  },
  {
    "CVE": "E2950",
    "CATEGORIA": "TÉCNICO DOCENTE AUXILIAR EDUCACION MEDIA SUPERIOR D.F. ¾ T. “B”",
    "CAT_SIMPLE": "TÉCNICO DOCENTE AUXILIAR",
    "ORD_CAT": 1200,
    "CT_AV": null
  },
  {
    "CVE": "E2951",
    "CATEGORIA": "TÉCNICO DOCENTE AUXILIAR EDUCACION MEDIA SUPERIOR FOR. ¾ T. “C”",
    "CAT_SIMPLE": "TÉCNICO DOCENTE AUXILIAR",
    "ORD_CAT": 1200,
    "CT_AV": null
  },
  {
    "CVE": "E2952",
    "CATEGORIA": "TÉCNICO DOCENTE AUXILIAR EDUCACION MEDIA SUPERIOR D.F. ¾ T. “C”",
    "CAT_SIMPLE": "TÉCNICO DOCENTE AUXILIAR",
    "ORD_CAT": 1200,
    "CT_AV": null
  },
  {
    "CVE": "E3031",
    "CATEGORIA": "TÉCNICO DOCENTE AUXILIAR  EDUCACION SUPERIOR FOR. T.C. “A”",
    "CAT_SIMPLE": "TÉCNICO DOCENTE AUXILIAR",
    "ORD_CAT": 1200,
    "CT_AV": null
  },
  {
    "CVE": "E3032",
    "CATEGORIA": "TÉCNICO DOCENTE AUXILIAR EDUCACION SUPERIOR D.F. T.C. “A”",
    "CAT_SIMPLE": "TÉCNICO DOCENTE AUXILIAR",
    "ORD_CAT": 1200,
    "CT_AV": null
  },
  {
    "CVE": "E3033",
    "CATEGORIA": "TÉCNICO DOCENTE AUXILIAR EDUCACION SUPERIOR FOR. T.C. “B”",
    "CAT_SIMPLE": "TÉCNICO DOCENTE AUXILIAR",
    "ORD_CAT": 1200,
    "CT_AV": null
  },
  {
    "CVE": "E3034",
    "CATEGORIA": "TÉCNICO DOCENTE AUXILIAR EDUCACION SUPERIOR D.F. T.C. “B”",
    "CAT_SIMPLE": "TÉCNICO DOCENTE AUXILIAR",
    "ORD_CAT": 1200,
    "CT_AV": null
  },
  {
    "CVE": "E3035",
    "CATEGORIA": "TÉCNICO DOCENTE AUXILIAR EDUCACION SUPERIOR FOR. T.C. “C”",
    "CAT_SIMPLE": "TÉCNICO DOCENTE AUXILIAR",
    "ORD_CAT": 1200,
    "CT_AV": null
  },
  {
    "CVE": "E3036",
    "CATEGORIA": "TÉCNICO DOCENTE AUXILIAR EDUCACION SUPERIOR D.F. T.C. “C”",
    "CAT_SIMPLE": "TÉCNICO DOCENTE AUXILIAR",
    "ORD_CAT": 1200,
    "CT_AV": null
  },
  {
    "CVE": "E3047",
    "CATEGORIA": "TÉCNICO DOCENTE AUXILIAR EDUCACION MEDIA SUPERIOR FOR. T.C. “A”",
    "CAT_SIMPLE": "TÉCNICO DOCENTE AUXILIAR",
    "ORD_CAT": 1200,
    "CT_AV": null
  },
  {
    "CVE": "E3048",
    "CATEGORIA": "TÉCNICO DOCENTE AUXILIAR EDUCACION MEDIA SUPERIOR D.F. T.C. “A”",
    "CAT_SIMPLE": "TÉCNICO DOCENTE AUXILIAR",
    "ORD_CAT": 1200,
    "CT_AV": null
  },
  {
    "CVE": "E3050",
    "CATEGORIA": "TÉCNICO DOCENTE AUXILIAR EDUCACION MEDIA SUPERIOR D.F. T.C. “B”",
    "CAT_SIMPLE": "TÉCNICO DOCENTE AUXILIAR",
    "ORD_CAT": 1200,
    "CT_AV": null
  },
  {
    "CVE": "E3051",
    "CATEGORIA": "TÉCNICO DOCENTE AUXILIAR EDUCACION MEDIA SUPERIOR FOR. T.C. “C”",
    "CAT_SIMPLE": "TÉCNICO DOCENTE AUXILIAR",
    "ORD_CAT": 1200,
    "CT_AV": null
  },
  {
    "CVE": "E3052",
    "CATEGORIA": "TÉCNICO DOCENTE AUXILIAR EDUCACION MEDIA SUPERIOR D.F. T.C. “C”",
    "CAT_SIMPLE": "TÉCNICO DOCENTE AUXILIAR",
    "ORD_CAT": 1200,
    "CT_AV": null
  },
  {
    "CVE": "E4039",
    "CATEGORIA": "TÉCNICO DOCENTE AUXILIAR EDUCACION MEDIA SUPERIOR FOR. T.C. “B”",
    "CAT_SIMPLE": "TÉCNICO DOCENTE AUXILIAR",
    "ORD_CAT": 1200,
    "CT_AV": null
  },
  {
    "CVE": "E2837",
    "CATEGORIA": "TÉCNICO DOCENTE ASOCIADO EDUCACION SUPERIOR FOR. ½ T. “A” ",
    "CAT_SIMPLE": "TÉCNICO DOCENTE ASOCIADO",
    "ORD_CAT": 1500,
    "CT_AV": null
  },
  {
    "CVE": "E2838",
    "CATEGORIA": "TÉCNICO DOCENTE ASOCIADO EDUCACION SUPERIOR D.F. ½ T. “A”",
    "CAT_SIMPLE": "TÉCNICO DOCENTE ASOCIADO",
    "ORD_CAT": 1500,
    "CT_AV": null
  },
  {
    "CVE": "E2839",
    "CATEGORIA": "TÉCNICO DOCENTE ASOCIADO EDUCACION SUPERIOR FOR. ½ T. “B” ",
    "CAT_SIMPLE": "TÉCNICO DOCENTE ASOCIADO",
    "ORD_CAT": 1500,
    "CT_AV": null
  },
  {
    "CVE": "E2840",
    "CATEGORIA": "TÉCNICO DOCENTE ASOCIADO EDUCACION SUPERIOR D.F. ½ T. “B”",
    "CAT_SIMPLE": "TÉCNICO DOCENTE ASOCIADO",
    "ORD_CAT": 1500,
    "CT_AV": null
  },
  {
    "CVE": "E2841",
    "CATEGORIA": "TÉCNICO DOCENTE ASOCIADO EDUCACION SUPERIOR FOR. ½ T. “C” ",
    "CAT_SIMPLE": "TÉCNICO DOCENTE ASOCIADO",
    "ORD_CAT": 1500,
    "CT_AV": null
  },
  {
    "CVE": "E2842",
    "CATEGORIA": "TÉCNICO DOCENTE ASOCIADO EDUCACION SUPERIOR D.F. ½ T. “C”",
    "CAT_SIMPLE": "TÉCNICO DOCENTE ASOCIADO",
    "ORD_CAT": 1500,
    "CT_AV": null
  },
  {
    "CVE": "E2853",
    "CATEGORIA": "TÉCNICO DOCENTE ASOCIADO EDUCACION MEDIA SUPERIOR FOR. ½ T. “A” ",
    "CAT_SIMPLE": "TÉCNICO DOCENTE ASOCIADO",
    "ORD_CAT": 1500,
    "CT_AV": null
  },
  {
    "CVE": "E2854",
    "CATEGORIA": "TÉCNICO DOCENTE ASOCIADO EDUCACION MEDIA SUPERIOR D.F. ½ T. “A”",
    "CAT_SIMPLE": "TÉCNICO DOCENTE ASOCIADO",
    "ORD_CAT": 1500,
    "CT_AV": null
  },
  {
    "CVE": "E2855",
    "CATEGORIA": "TÉCNICO DOCENTE ASOCIADO EDUCACION MEDIA SUPERIOR FOR. ½ T. “B” ",
    "CAT_SIMPLE": "TÉCNICO DOCENTE ASOCIADO",
    "ORD_CAT": 1500,
    "CT_AV": null
  },
  {
    "CVE": "E2856",
    "CATEGORIA": "TÉCNICO DOCENTE ASOCIADO EDUCACION MEDIA SUPERIOR D.F. ½ T. “B”",
    "CAT_SIMPLE": "TÉCNICO DOCENTE ASOCIADO",
    "ORD_CAT": 1500,
    "CT_AV": null
  },
  {
    "CVE": "E2857",
    "CATEGORIA": "TÉCNICO DOCENTE ASOCIADO EDUCACION MEDIA SUPERIOR FOR. ½ T. “C” ",
    "CAT_SIMPLE": "TÉCNICO DOCENTE ASOCIADO",
    "ORD_CAT": 1500,
    "CT_AV": null
  },
  {
    "CVE": "E2858",
    "CATEGORIA": "TÉCNICO DOCENTE ASOCIADO EDUCACION MEDIA SUPERIOR D.F. ½ T. “C”",
    "CAT_SIMPLE": "TÉCNICO DOCENTE ASOCIADO",
    "ORD_CAT": 1500,
    "CT_AV": null
  },
  {
    "CVE": "E2937",
    "CATEGORIA": "TÉCNICO DOCENTE ASOCIADO EDUCACION SUPERIOR FOR. ¾ T. “A”",
    "CAT_SIMPLE": "TÉCNICO DOCENTE ASOCIADO",
    "ORD_CAT": 1500,
    "CT_AV": null
  },
  {
    "CVE": "E2938",
    "CATEGORIA": "TÉCNICO DOCENTE ASOCIADO EDUCACION SUPERIOR D.F. ¾ T. “A”",
    "CAT_SIMPLE": "TÉCNICO DOCENTE ASOCIADO",
    "ORD_CAT": 1500,
    "CT_AV": null
  },
  {
    "CVE": "E2939",
    "CATEGORIA": "TÉCNICO DOCENTE ASOCIADO EDUCACION SUPERIOR FOR. ¾ T. “B”",
    "CAT_SIMPLE": "TÉCNICO DOCENTE ASOCIADO",
    "ORD_CAT": 1500,
    "CT_AV": null
  },
  {
    "CVE": "E2940",
    "CATEGORIA": "TÉCNICO DOCENTE ASOCIADO EDUCACION SUPERIOR D.F.. ¾ T. “B”",
    "CAT_SIMPLE": "TÉCNICO DOCENTE ASOCIADO",
    "ORD_CAT": 1500,
    "CT_AV": null
  },
  {
    "CVE": "E2941",
    "CATEGORIA": "TÉCNICO DOCENTE ASOCIADO EDUCACION SUPERIOR FOR. ¾ T. “C”",
    "CAT_SIMPLE": "TÉCNICO DOCENTE ASOCIADO",
    "ORD_CAT": 1500,
    "CT_AV": null
  },
  {
    "CVE": "E2942",
    "CATEGORIA": "TÉCNICO DOCENTE ASOCIADO EDUCACION SUPERIOR D.F. ¾ T. “C”",
    "CAT_SIMPLE": "TÉCNICO DOCENTE ASOCIADO",
    "ORD_CAT": 1500,
    "CT_AV": null
  },
  {
    "CVE": "E2953",
    "CATEGORIA": "TÉCNICO DOCENTE ASOCIADO EDUCACION MEDIA SUPERIOR FOR. ¾ T. “A” ",
    "CAT_SIMPLE": "TÉCNICO DOCENTE ASOCIADO",
    "ORD_CAT": 1500,
    "CT_AV": null
  },
  {
    "CVE": "E2954",
    "CATEGORIA": "TÉCNICO DOCENTE ASOCIADO EDUCACION MEDIA SUPERIOR D.F.  ¾ T. “A” ",
    "CAT_SIMPLE": "TÉCNICO DOCENTE ASOCIADO",
    "ORD_CAT": 1500,
    "CT_AV": null
  },
  {
    "CVE": "E2955",
    "CATEGORIA": "TÉCNICO DOCENTE ASOCIADO EDUCACION MEDIA SUPERIOR FOR. ¾ T. “B” ",
    "CAT_SIMPLE": "TÉCNICO DOCENTE ASOCIADO",
    "ORD_CAT": 1500,
    "CT_AV": null
  },
  {
    "CVE": "E2956",
    "CATEGORIA": "TÉCNICO DOCENTE ASOCIADO EDUCACION MEDIA SUPERIOR D.F.  ¾ T. “B” ",
    "CAT_SIMPLE": "TÉCNICO DOCENTE ASOCIADO",
    "ORD_CAT": 1500,
    "CT_AV": null
  },
  {
    "CVE": "E2957",
    "CATEGORIA": "TÉCNICO DOCENTE ASOCIADO EDUCACION MEDIA SUPERIOR FOR. ¾ T. “C” ",
    "CAT_SIMPLE": "TÉCNICO DOCENTE ASOCIADO",
    "ORD_CAT": 1500,
    "CT_AV": null
  },
  {
    "CVE": "E2958",
    "CATEGORIA": "TÉCNICO DOCENTE ASOCIADO EDUCACION MEDIA SUPERIOR D.F.  ¾ T. “C” ",
    "CAT_SIMPLE": "TÉCNICO DOCENTE ASOCIADO",
    "ORD_CAT": 1500,
    "CT_AV": null
  },
  {
    "CVE": "E3037",
    "CATEGORIA": "TÉCNICO DOCENTE ASOCIADO EDUCACION SUPERIOR FOR. T.C. “A”",
    "CAT_SIMPLE": "TÉCNICO DOCENTE ASOCIADO",
    "ORD_CAT": 1500,
    "CT_AV": null
  },
  {
    "CVE": "E3038",
    "CATEGORIA": "TÉCNICO DOCENTE ASOCIADO EDUCACION SUPERIOR D.F. T.C. “A”",
    "CAT_SIMPLE": "TÉCNICO DOCENTE ASOCIADO",
    "ORD_CAT": 1500,
    "CT_AV": null
  },
  {
    "CVE": "E3039",
    "CATEGORIA": "TÉCNICO DOCENTE ASOCIADO EDUCACION SUPERIOR FOR. T.C. “B”",
    "CAT_SIMPLE": "TÉCNICO DOCENTE ASOCIADO",
    "ORD_CAT": 1500,
    "CT_AV": null
  },
  {
    "CVE": "E3040",
    "CATEGORIA": "TÉCNICO DOCENTE ASOCIADO EDUCACION SUPERIOR D.F.. T.C. “B”",
    "CAT_SIMPLE": "TÉCNICO DOCENTE ASOCIADO",
    "ORD_CAT": 1500,
    "CT_AV": null
  },
  {
    "CVE": "E3041",
    "CATEGORIA": "TÉCNICO DOCENTE ASOCIADO EDUCACION SUPERIOR FOR. T.C. “C”",
    "CAT_SIMPLE": "TÉCNICO DOCENTE ASOCIADO",
    "ORD_CAT": 1500,
    "CT_AV": null
  },
  {
    "CVE": "E3042",
    "CATEGORIA": "TÉCNICO DOCENTE ASOCIADO EDUCACION SUPERIOR D.F. T.C. “C”",
    "CAT_SIMPLE": "TÉCNICO DOCENTE ASOCIADO",
    "ORD_CAT": 1500,
    "CT_AV": null
  },
  {
    "CVE": "E3053",
    "CATEGORIA": "TÉCNICO DOCENTE ASOCIADO EDUCACION MEDIA SUPERIOR FOR.  T.C. “A” ",
    "CAT_SIMPLE": "TÉCNICO DOCENTE ASOCIADO",
    "ORD_CAT": 1500,
    "CT_AV": null
  },
  {
    "CVE": "E3054",
    "CATEGORIA": "TÉCNICO DOCENTE ASOCIADO EDUCACION MEDIA SUPERIOR D.F. T.C. “A”",
    "CAT_SIMPLE": "TÉCNICO DOCENTE ASOCIADO",
    "ORD_CAT": 1500,
    "CT_AV": null
  },
  {
    "CVE": "E3055",
    "CATEGORIA": "TÉCNICO DOCENTE ASOCIADO EDUCACION MEDIA SUPERIOR FOR. T.C. “B”",
    "CAT_SIMPLE": "TÉCNICO DOCENTE ASOCIADO",
    "ORD_CAT": 1500,
    "CT_AV": null
  },
  {
    "CVE": "E3056",
    "CATEGORIA": "TÉCNICO DOCENTE ASOCIADO EDUCACION MEDIA SUPERIOR D.F. T.C. “B”",
    "CAT_SIMPLE": "TÉCNICO DOCENTE ASOCIADO",
    "ORD_CAT": 1500,
    "CT_AV": null
  },
  {
    "CVE": "E3057",
    "CATEGORIA": "TÉCNICO DOCENTE ASOCIADO EDUCACION MEDIA SUPERIOR FOR. T.C. “C”",
    "CAT_SIMPLE": "TÉCNICO DOCENTE ASOCIADO",
    "ORD_CAT": 1500,
    "CT_AV": null
  },
  {
    "CVE": "E3058",
    "CATEGORIA": "TÉCNICO DOCENTE ASOCIADO EDUCACION MEDIA SUPERIOR D.F. T.C. “C”",
    "CAT_SIMPLE": "TÉCNICO DOCENTE ASOCIADO",
    "ORD_CAT": 1500,
    "CT_AV": null
  },
  {
    "CVE": "E6138",
    "CATEGORIA": "TECNICO DOCENTE ASOCIADO \"A\" (EDUCACION SUPERIOR) 1/2 TIEMP",
    "CAT_SIMPLE": "TÉCNICO DOCENTE ASOCIADO",
    "ORD_CAT": 1500,
    "CT_AV": null
  },
  {
    "CVE": "E6140",
    "CATEGORIA": "TECNICO DOCENTE ASOCIADO \"B\" (EDUCACION SUPERIOR) 1/2 TIEMP",
    "CAT_SIMPLE": "TÉCNICO DOCENTE ASOCIADO",
    "ORD_CAT": 1500,
    "CT_AV": null
  },
  {
    "CVE": "E6142",
    "CATEGORIA": "TECNICO DOCENTE ASOCIADO \"C\" EDUCACION SUPERIOR 1/2 TIEMPO",
    "CAT_SIMPLE": "TÉCNICO DOCENTE ASOCIADO",
    "ORD_CAT": 1500,
    "CT_AV": null
  },
  {
    "CVE": "E6154",
    "CATEGORIA": "TECNICO DOCENTE ASOCIADO \"A\" (EDUCACION MEDIA SUPERIOR) 1/2 TIE",
    "CAT_SIMPLE": "TÉCNICO DOCENTE ASOCIADO",
    "ORD_CAT": 1500,
    "CT_AV": null
  },
  {
    "CVE": "E6238",
    "CATEGORIA": "TECNICO DOCENTE ASOCIADO \"A\" (EDUCACION SUPERIOR) 3/4 DE TI",
    "CAT_SIMPLE": "TÉCNICO DOCENTE ASOCIADO",
    "ORD_CAT": 1500,
    "CT_AV": null
  },
  {
    "CVE": "E6240",
    "CATEGORIA": "TECNICO DOCENTE ASOCIADO \"B\" (EDUCACION SUPERIOR) 3/4 DE TI",
    "CAT_SIMPLE": "TÉCNICO DOCENTE ASOCIADO",
    "ORD_CAT": 1500,
    "CT_AV": null
  },
  {
    "CVE": "E6242",
    "CATEGORIA": "TECNICO DOCENTE ASOCIADO \"C\" (EDUCACION SUPERIOR) 3/4 DE TI",
    "CAT_SIMPLE": "TÉCNICO DOCENTE ASOCIADO",
    "ORD_CAT": 1500,
    "CT_AV": null
  },
  {
    "CVE": "E6254",
    "CATEGORIA": "TECNICO DOCENTE ASOCIADO \"A\" (EDUCACION MEDIA SUPERIOR) 3/4 DE ",
    "CAT_SIMPLE": "TÉCNICO DOCENTE ASOCIADO",
    "ORD_CAT": 1500,
    "CT_AV": null
  },
  {
    "CVE": "E6338",
    "CATEGORIA": "TECNICO DOCENTE ASOCIADO \"A\" (EDUCACION SUPERIOR) TIEMPO CO",
    "CAT_SIMPLE": "TÉCNICO DOCENTE ASOCIADO",
    "ORD_CAT": 1500,
    "CT_AV": null
  },
  {
    "CVE": "E6340",
    "CATEGORIA": "TECNICO DOCENTE ASOCIADO \"B\" (EDUCACION SUPERIOR) TIEMPO CO",
    "CAT_SIMPLE": "TÉCNICO DOCENTE ASOCIADO",
    "ORD_CAT": 1500,
    "CT_AV": null
  },
  {
    "CVE": "E2843",
    "CATEGORIA": "TÉCNICO TITULAR EDUCACION SUPERIOR FOR. ½ T. “A”",
    "CAT_SIMPLE": "TÉCNICO DOCENTE TITULAR",
    "ORD_CAT": 1800,
    "CT_AV": null
  },
  {
    "CVE": "E2844",
    "CATEGORIA": "TÉCNICO TITULAR EDUCACION SUPERIOR D.F. ½ T. “A”",
    "CAT_SIMPLE": "TÉCNICO DOCENTE TITULAR",
    "ORD_CAT": 1800,
    "CT_AV": null
  },
  {
    "CVE": "E2845",
    "CATEGORIA": "TÉCNICO TITULAR EDUCACION SUPERIOR FOR. ½ T. “B”",
    "CAT_SIMPLE": "TÉCNICO DOCENTE TITULAR",
    "ORD_CAT": 1800,
    "CT_AV": null
  },
  {
    "CVE": "E2846",
    "CATEGORIA": "TÉCNICO TITULAR EDUCACION SUPERIOR D.F. ½ T. “B”",
    "CAT_SIMPLE": "TÉCNICO DOCENTE TITULAR",
    "ORD_CAT": 1800,
    "CT_AV": null
  },
  {
    "CVE": "E2865",
    "CATEGORIA": "TÉCNICO DOCENTE TITULAR EDUCACION MEDIA SUPERIOR FOR. ½ T. “A”",
    "CAT_SIMPLE": "TÉCNICO DOCENTE TITULAR",
    "ORD_CAT": 1800,
    "CT_AV": null
  },
  {
    "CVE": "E2866",
    "CATEGORIA": "TÉCNICO DOCENTE TITULAR EDUCACION MEDIA SUPERIOR D.F. ½ T. “A”",
    "CAT_SIMPLE": "TÉCNICO DOCENTE TITULAR",
    "ORD_CAT": 1800,
    "CT_AV": null
  },
  {
    "CVE": "E2867",
    "CATEGORIA": "TÉCNICO DOCENTE TITULAR EDUCACION MEDIA SUPERIOR FOR. ½ T. “B”",
    "CAT_SIMPLE": "TÉCNICO DOCENTE TITULAR",
    "ORD_CAT": 1800,
    "CT_AV": null
  },
  {
    "CVE": "E2868",
    "CATEGORIA": "TÉCNICO DOCENTE TITULAR EDUCACION MEDIA SUPERIOR D.F. ½ T. “B”",
    "CAT_SIMPLE": "TÉCNICO DOCENTE TITULAR",
    "ORD_CAT": 1800,
    "CT_AV": null
  },
  {
    "CVE": "E2943",
    "CATEGORIA": "TEC. TITULAR EDUCACION SUPERIOR FOR. ¾ T. “A”",
    "CAT_SIMPLE": "TÉCNICO DOCENTE TITULAR",
    "ORD_CAT": 1800,
    "CT_AV": null
  },
  {
    "CVE": "E2944",
    "CATEGORIA": "TEC. TITULAR EDUCACION SUPERIOR D.F. ¾ T. “A”",
    "CAT_SIMPLE": "TÉCNICO DOCENTE TITULAR",
    "ORD_CAT": 1800,
    "CT_AV": null
  },
  {
    "CVE": "E2945",
    "CATEGORIA": "TEC. TITULAR EDUCACION SUPERIOR FOR. ¾ T. “B”",
    "CAT_SIMPLE": "TÉCNICO DOCENTE TITULAR",
    "ORD_CAT": 1800,
    "CT_AV": null
  },
  {
    "CVE": "E2946",
    "CATEGORIA": "TEC. TITULAR EDUCACION SUPERIOR D.F. ¾ T. “B”",
    "CAT_SIMPLE": "TÉCNICO DOCENTE TITULAR",
    "ORD_CAT": 1800,
    "CT_AV": null
  },
  {
    "CVE": "E2965",
    "CATEGORIA": "TÉCNICO DOCENTE TITULAR EDUCACION MEDIA SUPERIOR FOR. ¾ T. “A”",
    "CAT_SIMPLE": "TÉCNICO DOCENTE TITULAR",
    "ORD_CAT": 1800,
    "CT_AV": null
  },
  {
    "CVE": "E2966",
    "CATEGORIA": "TÉCNICO DOCENTE TITULAR EDUCACION MEDIA SUPERIOR D.F. ¾ T. “A”",
    "CAT_SIMPLE": "TÉCNICO DOCENTE TITULAR",
    "ORD_CAT": 1800,
    "CT_AV": null
  },
  {
    "CVE": "E2967",
    "CATEGORIA": "TÉCNICO DOCENTE TITULAR EDUCACION MEDIA SUPERIOR FOR. ¾ T. “B”",
    "CAT_SIMPLE": "TÉCNICO DOCENTE TITULAR",
    "ORD_CAT": 1800,
    "CT_AV": null
  },
  {
    "CVE": "E2968",
    "CATEGORIA": "TÉCNICO DOCENTE TITULAR EDUCACION MEDIA SUPERIOR D.F. ¾ T. “B”",
    "CAT_SIMPLE": "TÉCNICO DOCENTE TITULAR",
    "ORD_CAT": 1800,
    "CT_AV": null
  },
  {
    "CVE": "E3043",
    "CATEGORIA": "TÉCNICO DOCENTE TITULAR EDUCACION SUPERIOR FOR. T.C. “A”",
    "CAT_SIMPLE": "TÉCNICO DOCENTE TITULAR",
    "ORD_CAT": 1800,
    "CT_AV": null
  },
  {
    "CVE": "E3044",
    "CATEGORIA": "TÉCNICO DOCENTE TITULAR EDUCACION SUPERIOR D.F. T.C. “A”",
    "CAT_SIMPLE": "TÉCNICO DOCENTE TITULAR",
    "ORD_CAT": 1800,
    "CT_AV": null
  },
  {
    "CVE": "E3045",
    "CATEGORIA": "TÉCNICO DOCENTE TITULAR EDUCACION SUPERIOR FOR. T.C. “B”",
    "CAT_SIMPLE": "TÉCNICO DOCENTE TITULAR",
    "ORD_CAT": 1800,
    "CT_AV": null
  },
  {
    "CVE": "E3046",
    "CATEGORIA": "TÉCNICO DOCENTE TITULAR EDUCACION SUPERIOR D.F. T.C. “B”",
    "CAT_SIMPLE": "TÉCNICO DOCENTE TITULAR",
    "ORD_CAT": 1800,
    "CT_AV": null
  },
  {
    "CVE": "E3065",
    "CATEGORIA": "TÉCNICO DOCENTE TITULAR EDUCACION MEDIA SUPERIOR FOR. T.C. “A”",
    "CAT_SIMPLE": "TÉCNICO DOCENTE TITULAR",
    "ORD_CAT": 1800,
    "CT_AV": null
  },
  {
    "CVE": "E3066",
    "CATEGORIA": "TÉCNICO DOCENTE TITULAR EDUCACION MEDIA SUPERIOR D.F. T. C.“A”",
    "CAT_SIMPLE": "TÉCNICO DOCENTE TITULAR",
    "ORD_CAT": 1800,
    "CT_AV": null
  },
  {
    "CVE": "E3067",
    "CATEGORIA": "TÉCNICO DOCENTE TITULAR EDUCACION MEDIA SUPERIOR FOR. T. C.“B”",
    "CAT_SIMPLE": "TÉCNICO DOCENTE TITULAR",
    "ORD_CAT": 1800,
    "CT_AV": null
  },
  {
    "CVE": "E3068",
    "CATEGORIA": "TÉCNICO DOCENTE TITULAR EDUCACION MEDIA SUPERIOR D.F. T. C.“B”",
    "CAT_SIMPLE": "TÉCNICO DOCENTE TITULAR",
    "ORD_CAT": 1800,
    "CT_AV": null
  },
  {
    "CVE": "E6246",
    "CATEGORIA": "TECNICO DOCENTE TITULAR \"B\" (EDUCACION SUPERIOR) 3/4 DE TIE",
    "CAT_SIMPLE": "TÉCNICO DOCENTE TITULAR",
    "ORD_CAT": 1800,
    "CT_AV": null
  },
  {
    "CVE": "E3101",
    "CATEGORIA": "PROFESOR DE ASIGNATURA EDUCACION SUPERIOR FOR.  “A” ",
    "CAT_SIMPLE": "PROFESOR DE ASIGNATURA",
    "ORD_CAT": 5100,
    "CT_AV": null
  },
  {
    "CVE": "E3102",
    "CATEGORIA": "PROFESOR DE ASIGNATURA EDUCACION SUPERIOR D.F. “A”",
    "CAT_SIMPLE": "PROFESOR DE ASIGNATURA",
    "ORD_CAT": 5100,
    "CT_AV": null
  },
  {
    "CVE": "E3103",
    "CATEGORIA": "PROFESOR DE ASIGNATURA EDUCACION SUPERIOR FOR. “B”",
    "CAT_SIMPLE": "PROFESOR DE ASIGNATURA",
    "ORD_CAT": 5100,
    "CT_AV": null
  },
  {
    "CVE": "E3104",
    "CATEGORIA": "PROFESOR DE ASIGNATURA EDUCACION SUPERIOR D.F. “B”",
    "CAT_SIMPLE": "PROFESOR DE ASIGNATURA",
    "ORD_CAT": 5100,
    "CT_AV": null
  },
  {
    "CVE": "E3105",
    "CATEGORIA": "PROFESOR DE ASIGNATURA EDUCACION MEDIA SUPERIOR FOR. “A”",
    "CAT_SIMPLE": "PROFESOR DE ASIGNATURA",
    "ORD_CAT": 5100,
    "CT_AV": null
  },
  {
    "CVE": "E3106",
    "CATEGORIA": "PROFESOR DE ASIGNATURA EDUCACION MEDIA SUPERIOR D.F. “A”",
    "CAT_SIMPLE": "PROFESOR DE ASIGNATURA",
    "ORD_CAT": 5100,
    "CT_AV": null
  },
  {
    "CVE": "E3107",
    "CATEGORIA": "PROFESOR DE ASIGNATURA EDUCACION MEDIA SUPERIOR FOR. “B”",
    "CAT_SIMPLE": "PROFESOR DE ASIGNATURA",
    "ORD_CAT": 5100,
    "CT_AV": null
  },
  {
    "CVE": "E3108",
    "CATEGORIA": "PROFESOR DE ASIGNATURA EDUCACION MEDIA SUPERIOR D.F. “B”",
    "CAT_SIMPLE": "PROFESOR DE ASIGNATURA",
    "ORD_CAT": 5100,
    "CT_AV": null
  },
  {
    "CVE": "E6016",
    "CATEGORIA": "PROFESOR DE ASIGNATURA \"A\" (EDUCACION MEDIA SUPERIOR)",
    "CAT_SIMPLE": "PROFESOR DE ASIGNATURA",
    "ORD_CAT": 5100,
    "CT_AV": null
  },
  {
    "CVE": "E6018",
    "CATEGORIA": "PROFESOR DE ASIGNATURA \"B\" (EDUCACION MEDIA SUPERIOR)",
    "CAT_SIMPLE": "PROFESOR DE ASIGNATURA",
    "ORD_CAT": 5100,
    "CT_AV": null
  },
  {
    "CVE": "E6020",
    "CATEGORIA": "PROFESOR DE ASIGNATURA \"A\" (EDUCACION SUPERIOR)",
    "CAT_SIMPLE": "PROFESOR DE ASIGNATURA",
    "ORD_CAT": 5100,
    "CT_AV": null
  },
  {
    "CVE": "E6022",
    "CATEGORIA": "PROFESOR DE ASIGNATURA \"B\" (EDUCACION SUPERIOR)",
    "CAT_SIMPLE": "PROFESOR DE ASIGNATURA",
    "ORD_CAT": 5100,
    "CT_AV": null
  },
  {
    "CVE": "E6024",
    "CATEGORIA": "PROFESOR DE ASIGNATURA \"C\" (EDUCACION MEDIA SUPERIOR)",
    "CAT_SIMPLE": "PROFESOR DE ASIGNATURA",
    "ORD_CAT": 5100,
    "CT_AV": null
  },
  {
    "CVE": "E6026",
    "CATEGORIA": "PROFESOR DE ASIGNATURA \"C\" (EDUCACION SUPERIOR)",
    "CAT_SIMPLE": "PROFESOR DE ASIGNATURA",
    "ORD_CAT": 5100,
    "CT_AV": null
  },
  {
    "CVE": "E2801",
    "CATEGORIA": "PROFESOR ASISTENTE EDUCACION SUPERIOR FOR. ½ T. “A”",
    "CAT_SIMPLE": "PROFESOR ASISTENTE",
    "ORD_CAT": 5300,
    "CT_AV": null
  },
  {
    "CVE": "E2802",
    "CATEGORIA": "PROFESOR ASISTENTE EDUCACION SUPERIOR D.F ½ T. “A”",
    "CAT_SIMPLE": "PROFESOR ASISTENTE",
    "ORD_CAT": 5300,
    "CT_AV": null
  },
  {
    "CVE": "E2803",
    "CATEGORIA": "PROFESOR ASISTENTE EDUCACION SUPERIOR FOR. ½ T. “B”",
    "CAT_SIMPLE": "PROFESOR ASISTENTE",
    "ORD_CAT": 5300,
    "CT_AV": null
  },
  {
    "CVE": "E2804",
    "CATEGORIA": "PROFESOR ASISTENTE EDUCACION SUPERIOR D.F. ½ T. “B”",
    "CAT_SIMPLE": "PROFESOR ASISTENTE",
    "ORD_CAT": 5300,
    "CT_AV": null
  },
  {
    "CVE": "E2805",
    "CATEGORIA": "PROFESOR ASISTENTE EDUCACION SUPERIOR FOR. ½ T. “C”",
    "CAT_SIMPLE": "PROFESOR ASISTENTE",
    "ORD_CAT": 5300,
    "CT_AV": null
  },
  {
    "CVE": "E2806",
    "CATEGORIA": "PROFESOR ASISTENTE EDUCACION SUPERIOR D.F. ½ T. “C”",
    "CAT_SIMPLE": "PROFESOR ASISTENTE",
    "ORD_CAT": 5300,
    "CT_AV": null
  },
  {
    "CVE": "E2819",
    "CATEGORIA": "PROFESOR ASISTE EDUCACION MEDIA SUPERIOR FOR. ½ T. “A”",
    "CAT_SIMPLE": "PROFESOR ASISTENTE",
    "ORD_CAT": 5300,
    "CT_AV": null
  },
  {
    "CVE": "E2820",
    "CATEGORIA": "PROFESOR ASISTE EDUCACION MEDIA SUPERIOR D.F. ½ T. “A”",
    "CAT_SIMPLE": "PROFESOR ASISTENTE",
    "ORD_CAT": 5300,
    "CT_AV": null
  },
  {
    "CVE": "E2821",
    "CATEGORIA": "PROFESOR ASISTE EDUCACION MEDIA SUPERIOR FOR. ½ T. “B”",
    "CAT_SIMPLE": "PROFESOR ASISTENTE",
    "ORD_CAT": 5300,
    "CT_AV": null
  },
  {
    "CVE": "E2822",
    "CATEGORIA": "PROFESOR ASISTE EDUCACION MEDIA SUPERIOR D.F. ½ T. “B”",
    "CAT_SIMPLE": "PROFESOR ASISTENTE",
    "ORD_CAT": 5300,
    "CT_AV": null
  },
  {
    "CVE": "E2859",
    "CATEGORIA": "PROFESOR ASISTE EDUCACION MEDIA SUPERIOR FOR. ½ T. “C”",
    "CAT_SIMPLE": "PROFESOR ASISTENTE",
    "ORD_CAT": 5300,
    "CT_AV": null
  },
  {
    "CVE": "E2860",
    "CATEGORIA": "PROFESOR ASISTE EDUCACION MEDIA SUPERIOR D.F. ½ T. “C”",
    "CAT_SIMPLE": "PROFESOR ASISTENTE",
    "ORD_CAT": 5300,
    "CT_AV": null
  },
  {
    "CVE": "E2901",
    "CATEGORIA": "PROFESOR ASISTENTE EDUCACION SUPERIOR FOR. ¾ T. “A”",
    "CAT_SIMPLE": "PROFESOR ASISTENTE",
    "ORD_CAT": 5300,
    "CT_AV": null
  },
  {
    "CVE": "E2902",
    "CATEGORIA": "PROFESOR ASISTENTE EDUCACION SUPERIOR D.F. ¾ T. “A”",
    "CAT_SIMPLE": "PROFESOR ASISTENTE",
    "ORD_CAT": 5300,
    "CT_AV": null
  },
  {
    "CVE": "E2903",
    "CATEGORIA": "PROFESOR ASISTENTE EDUCACION SUPERIOR FOR. ¾ T. “B”",
    "CAT_SIMPLE": "PROFESOR ASISTENTE",
    "ORD_CAT": 5300,
    "CT_AV": null
  },
  {
    "CVE": "E2904",
    "CATEGORIA": "PROFESOR ASISTENTE EDUCACION SUPERIOR D.F. ¾ T. “B”",
    "CAT_SIMPLE": "PROFESOR ASISTENTE",
    "ORD_CAT": 5300,
    "CT_AV": null
  },
  {
    "CVE": "E2905",
    "CATEGORIA": "PROFESOR ASISTENTE EDUCACION SUPERIOR FOR. ¾ T. “C”",
    "CAT_SIMPLE": "PROFESOR ASISTENTE",
    "ORD_CAT": 5300,
    "CT_AV": null
  },
  {
    "CVE": "E2906",
    "CATEGORIA": "PROFESOR ASISTENTE EDUCACION SUPERIOR D.F. ¾ T. “C”",
    "CAT_SIMPLE": "PROFESOR ASISTENTE",
    "ORD_CAT": 5300,
    "CT_AV": null
  },
  {
    "CVE": "E2919",
    "CATEGORIA": "PROFESOR ASISTENTE EDUCACION MEDIA SUPERIOR FOR. ¾ T. “A”",
    "CAT_SIMPLE": "PROFESOR ASISTENTE",
    "ORD_CAT": 5300,
    "CT_AV": null
  },
  {
    "CVE": "E2920",
    "CATEGORIA": "PROFESOR ASISTENTE EDUCACION MEDIA SUPERIOR D.F. ¾ T. “A”",
    "CAT_SIMPLE": "PROFESOR ASISTENTE",
    "ORD_CAT": 5300,
    "CT_AV": null
  },
  {
    "CVE": "E2921",
    "CATEGORIA": "PROFESOR ASISTENTE EDUCACION MEDIA SUPERIOR FOR. ¾ T. “B”",
    "CAT_SIMPLE": "PROFESOR ASISTENTE",
    "ORD_CAT": 5300,
    "CT_AV": null
  },
  {
    "CVE": "E2922",
    "CATEGORIA": "PROFESOR ASISTENTE EDUCACION MEDIA SUPERIOR D.F. ¾ T. “B”",
    "CAT_SIMPLE": "PROFESOR ASISTENTE",
    "ORD_CAT": 5300,
    "CT_AV": null
  },
  {
    "CVE": "E2959",
    "CATEGORIA": "PROFESOR ASISTENTE EDUCACION MEDIA SUPERIOR FOR. ¾ T. “C”",
    "CAT_SIMPLE": "PROFESOR ASISTENTE",
    "ORD_CAT": 5300,
    "CT_AV": null
  },
  {
    "CVE": "E2960",
    "CATEGORIA": "PROFESOR ASISTENTE EDUCACION MEDIA SUPERIOR D.F. ¾ T. “C”",
    "CAT_SIMPLE": "PROFESOR ASISTENTE",
    "ORD_CAT": 5300,
    "CT_AV": null
  },
  {
    "CVE": "E3001",
    "CATEGORIA": "PROFESOR ASISTENTE EDUCACION SUPERIOR FOR. T.C. “A”",
    "CAT_SIMPLE": "PROFESOR ASISTENTE",
    "ORD_CAT": 5300,
    "CT_AV": null
  },
  {
    "CVE": "E3002",
    "CATEGORIA": "PROFESOR ASISTENTE EDUCACION SUPERIOR D.F. T.C. “A”",
    "CAT_SIMPLE": "PROFESOR ASISTENTE",
    "ORD_CAT": 5300,
    "CT_AV": null
  },
  {
    "CVE": "E3003",
    "CATEGORIA": "PROFESOR ASISTENTE EDUCACION SUPERIOR FOR. T.C. “B”",
    "CAT_SIMPLE": "PROFESOR ASISTENTE",
    "ORD_CAT": 5300,
    "CT_AV": null
  },
  {
    "CVE": "E3004",
    "CATEGORIA": "PROFESOR ASISTENTE EDUCACION SUPERIOR D.F. T.C. “B”",
    "CAT_SIMPLE": "PROFESOR ASISTENTE",
    "ORD_CAT": 5300,
    "CT_AV": null
  },
  {
    "CVE": "E3005",
    "CATEGORIA": "PROFESOR ASISTENTE EDUCACION SUPERIOR FOR. T.C. “C”",
    "CAT_SIMPLE": "PROFESOR ASISTENTE",
    "ORD_CAT": 5300,
    "CT_AV": null
  },
  {
    "CVE": "E3006",
    "CATEGORIA": "PROFESOR ASISTENTE EDUCACION SUPERIOR D.F. T.C. “C”",
    "CAT_SIMPLE": "PROFESOR ASISTENTE",
    "ORD_CAT": 5300,
    "CT_AV": null
  },
  {
    "CVE": "E3019",
    "CATEGORIA": "PROFESOR ASISTENTE EDUCACION MEDIA SUPERIOR FOR. T.C. “A”",
    "CAT_SIMPLE": "PROFESOR ASISTENTE",
    "ORD_CAT": 5300,
    "CT_AV": null
  },
  {
    "CVE": "E3020",
    "CATEGORIA": "PROFESOR ASISTENTE EDUCACION MEDIA SUPERIOR D.F. T.C. “A”",
    "CAT_SIMPLE": "PROFESOR ASISTENTE",
    "ORD_CAT": 5300,
    "CT_AV": null
  },
  {
    "CVE": "E3021",
    "CATEGORIA": "PROFESOR ASISTENTE EDUCACION MEDIA SUPERIOR FOR. T.C. “B”",
    "CAT_SIMPLE": "PROFESOR ASISTENTE",
    "ORD_CAT": 5300,
    "CT_AV": null
  },
  {
    "CVE": "E3022",
    "CATEGORIA": "PROFESOR ASISTENTE EDUCACION MEDIA SUPERIOR D.F. T.C. “B”",
    "CAT_SIMPLE": "PROFESOR ASISTENTE",
    "ORD_CAT": 5300,
    "CT_AV": null
  },
  {
    "CVE": "E3059",
    "CATEGORIA": "PROFESOR ASISTENTE EDUCACION MEDIA SUPERIOR FOR. T.C. “C”",
    "CAT_SIMPLE": "PROFESOR ASISTENTE",
    "ORD_CAT": 5300,
    "CT_AV": null
  },
  {
    "CVE": "E3060",
    "CATEGORIA": "PROFESOR ASISTENTE EDUCACION MEDIA SUPERIOR D.F. T.C. “C”",
    "CAT_SIMPLE": "PROFESOR ASISTENTE",
    "ORD_CAT": 5300,
    "CT_AV": null
  },
  {
    "CVE": "E2807",
    "CATEGORIA": "PROFESOR ASOCIADO EDUCACION SUPERIOR FOR. ½ T. ”A”",
    "CAT_SIMPLE": "PROFESOR ASOCIADO",
    "ORD_CAT": 5500,
    "CT_AV": null
  },
  {
    "CVE": "E2808",
    "CATEGORIA": "PROFESOR ASOCIADO EDUCACION SUPERIOR D.F. ½ T. ”A”",
    "CAT_SIMPLE": "PROFESOR ASOCIADO",
    "ORD_CAT": 5500,
    "CT_AV": null
  },
  {
    "CVE": "E2809",
    "CATEGORIA": "PROFESOR ASOCIADO EDUCACION SUPERIOR FOR. ½ T. ”B”",
    "CAT_SIMPLE": "PROFESOR ASOCIADO",
    "ORD_CAT": 5500,
    "CT_AV": null
  },
  {
    "CVE": "E2810",
    "CATEGORIA": "PROFESOR ASOCIADO EDUCACION SUPERIOR D.F. ½ T. ”B”",
    "CAT_SIMPLE": "PROFESOR ASOCIADO",
    "ORD_CAT": 5500,
    "CT_AV": null
  },
  {
    "CVE": "E2811",
    "CATEGORIA": "PROFESOR ASOCIADO EDUCACION SUPERIOR FOR. ½ T. ”C”",
    "CAT_SIMPLE": "PROFESOR ASOCIADO",
    "ORD_CAT": 5500,
    "CT_AV": null
  },
  {
    "CVE": "E2812",
    "CATEGORIA": "PROFESOR ASOCIADO EDUCACION SUPERIOR D.F. ½ T. ”C”",
    "CAT_SIMPLE": "PROFESOR ASOCIADO",
    "ORD_CAT": 5500,
    "CT_AV": null
  },
  {
    "CVE": "E2823",
    "CATEGORIA": "PROFESOR ASOCIADO EDUCACION MEDIA SUPERIOR FOR. ½ T. “A”",
    "CAT_SIMPLE": "PROFESOR ASOCIADO",
    "ORD_CAT": 5500,
    "CT_AV": null
  },
  {
    "CVE": "E2824",
    "CATEGORIA": "PROFESOR ASOCIADO EDUCACION MEDIA SUPERIOR D.F. ½ T. “A”",
    "CAT_SIMPLE": "PROFESOR ASOCIADO",
    "ORD_CAT": 5500,
    "CT_AV": null
  },
  {
    "CVE": "E2825",
    "CATEGORIA": "PROFESOR ASOCIADO EDUCACION MEDIA SUPERIOR FOR. ½ T. “B”",
    "CAT_SIMPLE": "PROFESOR ASOCIADO",
    "ORD_CAT": 5500,
    "CT_AV": null
  },
  {
    "CVE": "E2826",
    "CATEGORIA": "PROFESOR ASOCIADO EDUCACION MEDIA SUPERIOR D.F. ½ T. “B”",
    "CAT_SIMPLE": "PROFESOR ASOCIADO",
    "ORD_CAT": 5500,
    "CT_AV": null
  },
  {
    "CVE": "E2861",
    "CATEGORIA": "PROFESOR ASOCIADO EDUCACION MEDIA SUPERIOR FOR. ½ T. “C”",
    "CAT_SIMPLE": "PROFESOR ASOCIADO",
    "ORD_CAT": 5500,
    "CT_AV": null
  },
  {
    "CVE": "E2862",
    "CATEGORIA": "PROFESOR ASOCIADO EDUCACION MEDIA SUPERIOR D.F. ½ T. “C”",
    "CAT_SIMPLE": "PROFESOR ASOCIADO",
    "ORD_CAT": 5500,
    "CT_AV": null
  },
  {
    "CVE": "E2907",
    "CATEGORIA": "PROFESOR ASOCIADO EDUCACION SUPERIOR FOR. ¾ T. “A”",
    "CAT_SIMPLE": "PROFESOR ASOCIADO",
    "ORD_CAT": 5500,
    "CT_AV": null
  },
  {
    "CVE": "E2908",
    "CATEGORIA": "PROFESOR ASOCIADO EDUCACION SUPERIOR D.F. ¾ T. “A”",
    "CAT_SIMPLE": "PROFESOR ASOCIADO",
    "ORD_CAT": 5500,
    "CT_AV": null
  },
  {
    "CVE": "E2909",
    "CATEGORIA": "PROFESOR ASOCIADO EDUCACION SUPERIOR FOR. ¾ T. “B”",
    "CAT_SIMPLE": "PROFESOR ASOCIADO",
    "ORD_CAT": 5500,
    "CT_AV": null
  },
  {
    "CVE": "E2910",
    "CATEGORIA": "PROFESOR ASOCIADO EDUCACION SUPERIOR D.F. ¾ T. “B”",
    "CAT_SIMPLE": "PROFESOR ASOCIADO",
    "ORD_CAT": 5500,
    "CT_AV": null
  },
  {
    "CVE": "E2911",
    "CATEGORIA": "PROFESOR ASOCIADO EDUCACION SUPERIOR FOR. ¾ T. “C”",
    "CAT_SIMPLE": "PROFESOR ASOCIADO",
    "ORD_CAT": 5500,
    "CT_AV": null
  },
  {
    "CVE": "E2912",
    "CATEGORIA": "PROFESOR ASOCIADO EDUCACION SUPERIOR D.F. ¾ T. “C”",
    "CAT_SIMPLE": "PROFESOR ASOCIADO",
    "ORD_CAT": 5500,
    "CT_AV": null
  },
  {
    "CVE": "E2923",
    "CATEGORIA": "PROFESOR ASOCIADO EDUCACION MEDIA SUPERIOR FOR. ¾ T. “A”",
    "CAT_SIMPLE": "PROFESOR ASOCIADO",
    "ORD_CAT": 5500,
    "CT_AV": null
  },
  {
    "CVE": "E2924",
    "CATEGORIA": "PROFESOR ASOCIADO EDUCACION MEDIA SUPERIOR D.F. ¾ T. “A”",
    "CAT_SIMPLE": "PROFESOR ASOCIADO",
    "ORD_CAT": 5500,
    "CT_AV": null
  },
  {
    "CVE": "E2925",
    "CATEGORIA": "PROFESOR ASOCIADO EDUCACION MEDIA SUPERIOR FOR. ¾ T. “B”",
    "CAT_SIMPLE": "PROFESOR ASOCIADO",
    "ORD_CAT": 5500,
    "CT_AV": null
  },
  {
    "CVE": "E2926",
    "CATEGORIA": "PROFESOR ASOCIADO EDUCACION MEDIA SUPERIOR D.F. ¾ T. “B”",
    "CAT_SIMPLE": "PROFESOR ASOCIADO",
    "ORD_CAT": 5500,
    "CT_AV": null
  },
  {
    "CVE": "E2961",
    "CATEGORIA": "PROFESOR ASOCIADO EDUCACION MEDIA SUPERIOR FOR. ¾ T. “C”",
    "CAT_SIMPLE": "PROFESOR ASOCIADO",
    "ORD_CAT": 5500,
    "CT_AV": null
  },
  {
    "CVE": "E2962",
    "CATEGORIA": "PROFESOR ASOCIADO EDUCACION MEDIA SUPERIOR D.F. ¾ T. “C”",
    "CAT_SIMPLE": "PROFESOR ASOCIADO",
    "ORD_CAT": 5500,
    "CT_AV": null
  },
  {
    "CVE": "E3007",
    "CATEGORIA": "PROFESOR ASOCIADO EDUCACION SUPERIOR FOR. T.C. “A”",
    "CAT_SIMPLE": "PROFESOR ASOCIADO",
    "ORD_CAT": 5500,
    "CT_AV": null
  },
  {
    "CVE": "E3008",
    "CATEGORIA": "PROFESOR ASOCIADO EDUCACION SUPERIOR D.F. T.C. “A”",
    "CAT_SIMPLE": "PROFESOR ASOCIADO",
    "ORD_CAT": 5500,
    "CT_AV": null
  },
  {
    "CVE": "E3009",
    "CATEGORIA": "PROFESOR ASOCIADO EDUCACION SUPERIOR FOR. T.C. “B”",
    "CAT_SIMPLE": "PROFESOR ASOCIADO",
    "ORD_CAT": 5500,
    "CT_AV": null
  },
  {
    "CVE": "E3010",
    "CATEGORIA": "PROFESOR ASOCIADO EDUCACION SUPERIOR D.F.. T.C. “B”",
    "CAT_SIMPLE": "PROFESOR ASOCIADO",
    "ORD_CAT": 5500,
    "CT_AV": null
  },
  {
    "CVE": "E3011",
    "CATEGORIA": "PROFESOR ASOCIADO EDUCACION SUPERIOR FOR. T.C. “C”",
    "CAT_SIMPLE": "PROFESOR ASOCIADO",
    "ORD_CAT": 5500,
    "CT_AV": null
  },
  {
    "CVE": "E3012",
    "CATEGORIA": "PROFESOR ASOCIADO EDUCACION SUPERIOR D.F. T.C. “C”",
    "CAT_SIMPLE": "PROFESOR ASOCIADO",
    "ORD_CAT": 5500,
    "CT_AV": null
  },
  {
    "CVE": "E3023",
    "CATEGORIA": "PROFESOR ASOCIADO EDUCACION MEDIA SUPERIOR FOR. T.C. “A”",
    "CAT_SIMPLE": "PROFESOR ASOCIADO",
    "ORD_CAT": 5500,
    "CT_AV": null
  },
  {
    "CVE": "E3024",
    "CATEGORIA": "PROFESOR ASOCIADO EDUCACION MEDIA SUPERIOR D.F. T.C. “A”",
    "CAT_SIMPLE": "PROFESOR ASOCIADO",
    "ORD_CAT": 5500,
    "CT_AV": null
  },
  {
    "CVE": "E3025",
    "CATEGORIA": "PROFESOR ASOCIADO EDUCACION MEDIA SUPERIOR FOR. T.C. “B”",
    "CAT_SIMPLE": "PROFESOR ASOCIADO",
    "ORD_CAT": 5500,
    "CT_AV": null
  },
  {
    "CVE": "E3026",
    "CATEGORIA": "PROFESOR ASOCIADO EDUCACION MEDIA SUPERIOR D.F. T.C. “B”",
    "CAT_SIMPLE": "PROFESOR ASOCIADO",
    "ORD_CAT": 5500,
    "CT_AV": null
  },
  {
    "CVE": "E3061",
    "CATEGORIA": "PROFESOR ASOCIADO EDUCACION MEDIA SUPERIOR FOR. T.C. “C”",
    "CAT_SIMPLE": "PROFESOR ASOCIADO",
    "ORD_CAT": 5500,
    "CT_AV": null
  },
  {
    "CVE": "E3062",
    "CATEGORIA": "PROFESOR ASOCIADO EDUCACION MEDIA SUPERIOR D.F. T.C. “C”",
    "CAT_SIMPLE": "PROFESOR ASOCIADO",
    "ORD_CAT": 5500,
    "CT_AV": null
  },
  {
    "CVE": "E3201",
    "CATEGORIA": "PROFESOR ASOCIADO EDUCACION MEDIA SUPERIOR FOR. “BP”",
    "CAT_SIMPLE": "PROFESOR ASOCIADO",
    "ORD_CAT": 5500,
    "CT_AV": null
  },
  {
    "CVE": "E3202",
    "CATEGORIA": "PROFESOR ASOCIADO EDUCACION MEDIA SUPERIOR D.F. “BP”",
    "CAT_SIMPLE": "PROFESOR ASOCIADO",
    "ORD_CAT": 5500,
    "CT_AV": null
  },
  {
    "CVE": "E3203",
    "CATEGORIA": "PROFESOR ASOCIADO EDUCACION MEDIA SUPERIOR FOR. “CP”",
    "CAT_SIMPLE": "PROFESOR ASOCIADO",
    "ORD_CAT": 5500,
    "CT_AV": null
  },
  {
    "CVE": "E3204",
    "CATEGORIA": "PROFESOR ASOCIADO EDUCACION MEDIA SUPERIOR D.F. “CP”",
    "CAT_SIMPLE": "PROFESOR ASOCIADO",
    "ORD_CAT": 5500,
    "CT_AV": null
  },
  {
    "CVE": "E6108",
    "CATEGORIA": "PROFESOR ASOCIADO \"A\" (EDUCACION SUPERIOR) 1/2 TIEMPO",
    "CAT_SIMPLE": "PROFESOR ASOCIADO",
    "ORD_CAT": 5500,
    "CT_AV": null
  },
  {
    "CVE": "E6110",
    "CATEGORIA": "PROFESOR ASOCIADO \"B\" (EDUCACION SUPERIOR) 1/2 TIEMPO",
    "CAT_SIMPLE": "PROFESOR ASOCIADO",
    "ORD_CAT": 5500,
    "CT_AV": null
  },
  {
    "CVE": "E6112",
    "CATEGORIA": "PROFESOR ASOCIADO \"C\" (EDUCACION SUPERIOR) 1/2 TIEMPO",
    "CAT_SIMPLE": "PROFESOR ASOCIADO",
    "ORD_CAT": 5500,
    "CT_AV": null
  },
  {
    "CVE": "E6208",
    "CATEGORIA": "PROFESOR ASOCIADO \"A\" (EDUCACION SUPERIOR) 3/4 DE TIEMPO",
    "CAT_SIMPLE": "PROFESOR ASOCIADO",
    "ORD_CAT": 5500,
    "CT_AV": null
  },
  {
    "CVE": "E6210",
    "CATEGORIA": "PROFESOR ASOCIADO \"B\" (EDUCACION SUPERIOR) 3/4 DE TIEMPO",
    "CAT_SIMPLE": "PROFESOR ASOCIADO",
    "ORD_CAT": 5500,
    "CT_AV": null
  },
  {
    "CVE": "E6224",
    "CATEGORIA": "PROFESOR ASOCIADO \"A\" (EDUCACION MEDIA SUPERIOR) 3/4 DE TIEMPO",
    "CAT_SIMPLE": "PROFESOR ASOCIADO",
    "ORD_CAT": 5500,
    "CT_AV": null
  },
  {
    "CVE": "E6308",
    "CATEGORIA": "PROFESOR ASOCIADO \"A\" (EDUCACION SUPERIOR) TIEMPO COMPLETO",
    "CAT_SIMPLE": "PROFESOR ASOCIADO",
    "ORD_CAT": 5500,
    "CT_AV": null
  },
  {
    "CVE": "E6310",
    "CATEGORIA": "PROFESOR ASOCIADO \"B\" (EDUCACION SUPERIOR) TIEMPO COMPLETO",
    "CAT_SIMPLE": "PROFESOR ASOCIADO",
    "ORD_CAT": 5500,
    "CT_AV": null
  },
  {
    "CVE": "E6312",
    "CATEGORIA": "PROFESOR ASOCIADO \"C\" (EDUCACION SUPERIOR) TIEMPO COMPLETO",
    "CAT_SIMPLE": "PROFESOR ASOCIADO",
    "ORD_CAT": 5500,
    "CT_AV": null
  },
  {
    "CVE": "E2813",
    "CATEGORIA": "PROFESOR TITULAR EDUCACION SUPERIOR FOR. ½ T. “A”",
    "CAT_SIMPLE": "PROFESOR TITULAR",
    "ORD_CAT": 5800,
    "CT_AV": null
  },
  {
    "CVE": "E2814",
    "CATEGORIA": "PROFESOR TITULAR EDUCACION SUPERIOR D.F. ½ T. “A”",
    "CAT_SIMPLE": "PROFESOR TITULAR",
    "ORD_CAT": 5800,
    "CT_AV": null
  },
  {
    "CVE": "E2815",
    "CATEGORIA": "PROFESOR TITULAR EDUCACION SUPERIOR FOR. ½ T. “B”",
    "CAT_SIMPLE": "PROFESOR TITULAR",
    "ORD_CAT": 5800,
    "CT_AV": null
  },
  {
    "CVE": "E2816",
    "CATEGORIA": "PROFESOR TITULAR EDUCACION SUPERIOR D.F. ½ T. “B”",
    "CAT_SIMPLE": "PROFESOR TITULAR",
    "ORD_CAT": 5800,
    "CT_AV": null
  },
  {
    "CVE": "E2817",
    "CATEGORIA": "PROFESOR TITULAR EDUCACION SUPERIOR FOR. ½ T. “C”",
    "CAT_SIMPLE": "PROFESOR TITULAR",
    "ORD_CAT": 5800,
    "CT_AV": null
  },
  {
    "CVE": "E2818",
    "CATEGORIA": "PROFESOR TITULAR EDUCACION SUPERIOR D.F. ½ T. “C”",
    "CAT_SIMPLE": "PROFESOR TITULAR",
    "ORD_CAT": 5800,
    "CT_AV": null
  },
  {
    "CVE": "E2827",
    "CATEGORIA": "PROFESOR TITULAR EDUCACION MEDIA SUPERIOR FOR. ½ T. “A”",
    "CAT_SIMPLE": "PROFESOR TITULAR",
    "ORD_CAT": 5800,
    "CT_AV": null
  },
  {
    "CVE": "E2828",
    "CATEGORIA": "PROFESOR TITULAR EDUCACION MEDIA SUPERIOR D.F. ½ T. “A”",
    "CAT_SIMPLE": "PROFESOR TITULAR",
    "ORD_CAT": 5800,
    "CT_AV": null
  },
  {
    "CVE": "E2829",
    "CATEGORIA": "PROFESOR TITULAR EDUCACION MEDIA SUPERIOR FOR ½ T. “B”",
    "CAT_SIMPLE": "PROFESOR TITULAR",
    "ORD_CAT": 5800,
    "CT_AV": null
  },
  {
    "CVE": "E2830",
    "CATEGORIA": "PROFESOR TITULAR EDUCACION MEDIA SUPERIOR D.F. ½ T. “B”",
    "CAT_SIMPLE": "PROFESOR TITULAR",
    "ORD_CAT": 5800,
    "CT_AV": null
  },
  {
    "CVE": "E2863",
    "CATEGORIA": "PROFESOR TITULAR EDUCACION MEDIA SUPERIOR FOR. ½ T. “C”",
    "CAT_SIMPLE": "PROFESOR TITULAR",
    "ORD_CAT": 5800,
    "CT_AV": null
  },
  {
    "CVE": "E2864",
    "CATEGORIA": "PROFESOR TITULAR EDUCACION MEDIA SUPERIOR D.F. ½ T. “C”",
    "CAT_SIMPLE": "PROFESOR TITULAR",
    "ORD_CAT": 5800,
    "CT_AV": null
  },
  {
    "CVE": "E2913",
    "CATEGORIA": "PROFESOR TITULAR EDUCACION SUPERIOR FOR. ¾ T. “A”",
    "CAT_SIMPLE": "PROFESOR TITULAR",
    "ORD_CAT": 5800,
    "CT_AV": null
  },
  {
    "CVE": "E2914",
    "CATEGORIA": "PROFESOR TITULAR EDUCACION SUPERIOR D.F. ¾ T. “A”",
    "CAT_SIMPLE": "PROFESOR TITULAR",
    "ORD_CAT": 5800,
    "CT_AV": null
  },
  {
    "CVE": "E2915",
    "CATEGORIA": "PROFESOR TITULAR EDUCACION SUPERIOR FOR. ¾ T. “B”",
    "CAT_SIMPLE": "PROFESOR TITULAR",
    "ORD_CAT": 5800,
    "CT_AV": null
  },
  {
    "CVE": "E2916",
    "CATEGORIA": "PROFESOR TITULAR EDUCACION SUPERIOR D.F. ¾ T. “B”",
    "CAT_SIMPLE": "PROFESOR TITULAR",
    "ORD_CAT": 5800,
    "CT_AV": null
  },
  {
    "CVE": "E2917",
    "CATEGORIA": "PROFESOR TITULAR EDUCACION SUPERIOR FOR. ¾ T. “C”",
    "CAT_SIMPLE": "PROFESOR TITULAR",
    "ORD_CAT": 5800,
    "CT_AV": null
  },
  {
    "CVE": "E2918",
    "CATEGORIA": "PROFESOR TITULAR EDUCACION SUPERIOR D.F. ¾ T. “C”",
    "CAT_SIMPLE": "PROFESOR TITULAR",
    "ORD_CAT": 5800,
    "CT_AV": null
  },
  {
    "CVE": "E2927",
    "CATEGORIA": "PROFESOR TITULAR EDUCACION MEDIA SUPERIOR FOR. ¾ T. “A”",
    "CAT_SIMPLE": "PROFESOR TITULAR",
    "ORD_CAT": 5800,
    "CT_AV": null
  },
  {
    "CVE": "E2928",
    "CATEGORIA": "PROFESOR TITULAR EDUCACION MEDIA SUPERIOR D.F. ¾ T. “A”",
    "CAT_SIMPLE": "PROFESOR TITULAR",
    "ORD_CAT": 5800,
    "CT_AV": null
  },
  {
    "CVE": "E2929",
    "CATEGORIA": "PROFESOR TITULAR EDUCACION MEDIA SUPERIOR FOR. ¾ T. “B”",
    "CAT_SIMPLE": "PROFESOR TITULAR",
    "ORD_CAT": 5800,
    "CT_AV": null
  },
  {
    "CVE": "E2930",
    "CATEGORIA": "PROFESOR TITULAR EDUCACION MEDIA SUPERIOR D.F. ¾ T. “B”",
    "CAT_SIMPLE": "PROFESOR TITULAR",
    "ORD_CAT": 5800,
    "CT_AV": null
  },
  {
    "CVE": "E2963",
    "CATEGORIA": "PROFESOR TITULAR EDUCACION MEDIA SUPERIOR FOR. ¾ T. “C”",
    "CAT_SIMPLE": "PROFESOR TITULAR",
    "ORD_CAT": 5800,
    "CT_AV": null
  },
  {
    "CVE": "E2964",
    "CATEGORIA": "PROFESOR TITULAR EDUCACION MEDIA SUPERIOR D.F. ¾ T. “C”",
    "CAT_SIMPLE": "PROFESOR TITULAR",
    "ORD_CAT": 5800,
    "CT_AV": null
  },
  {
    "CVE": "E3013",
    "CATEGORIA": "PROFESOR TITULAR EDUCACION SUPERIOR FOR. T.C. “A”",
    "CAT_SIMPLE": "PROFESOR TITULAR",
    "ORD_CAT": 5800,
    "CT_AV": null
  },
  {
    "CVE": "E3014",
    "CATEGORIA": "PROFESOR TITULAR EDUCACION SUPERIOR D.F. T.C. “A”",
    "CAT_SIMPLE": "PROFESOR TITULAR",
    "ORD_CAT": 5800,
    "CT_AV": null
  },
  {
    "CVE": "E3015",
    "CATEGORIA": "PROFESOR TITULAR EDUCACION SUPERIOR FOR. T.C. “B”",
    "CAT_SIMPLE": "PROFESOR TITULAR",
    "ORD_CAT": 5800,
    "CT_AV": null
  },
  {
    "CVE": "E3016",
    "CATEGORIA": "PROFESOR TITULAR EDUCACION SUPERIOR D.F. T. C. “B”",
    "CAT_SIMPLE": "PROFESOR TITULAR",
    "ORD_CAT": 5800,
    "CT_AV": null
  },
  {
    "CVE": "E3017",
    "CATEGORIA": "PROFESOR TITULAR EDUCACION SUPERIOR FOR. T.C. “C”",
    "CAT_SIMPLE": "PROFESOR TITULAR",
    "ORD_CAT": 5800,
    "CT_AV": null
  },
  {
    "CVE": "E3018",
    "CATEGORIA": "PROFESOR TITULAR EDUCACION SUPERIOR D.F. T.C. “C”",
    "CAT_SIMPLE": "PROFESOR TITULAR",
    "ORD_CAT": 5800,
    "CT_AV": null
  },
  {
    "CVE": "E3027",
    "CATEGORIA": "PROFESOR TITULAR EDUCACION MEDIA SUPERIOR FOR. T.C. “A”",
    "CAT_SIMPLE": "PROFESOR TITULAR",
    "ORD_CAT": 5800,
    "CT_AV": null
  },
  {
    "CVE": "E3028",
    "CATEGORIA": "PROFESOR TITULAR EDUCACION MEDIA SUPERIOR D.F. T.C. “A”",
    "CAT_SIMPLE": "PROFESOR TITULAR",
    "ORD_CAT": 5800,
    "CT_AV": null
  },
  {
    "CVE": "E3029",
    "CATEGORIA": "PROFESOR TITULAR EDUCACION MEDIA SUPERIOR FOR. T.C. “B”",
    "CAT_SIMPLE": "PROFESOR TITULAR",
    "ORD_CAT": 5800,
    "CT_AV": null
  },
  {
    "CVE": "E3030",
    "CATEGORIA": "PROFESOR TITULAR EDUCACION MEDIA SUPERIOR D.F. T. C. “B”",
    "CAT_SIMPLE": "PROFESOR TITULAR",
    "ORD_CAT": 5800,
    "CT_AV": null
  },
  {
    "CVE": "E3063",
    "CATEGORIA": "PROFESOR TITULAR EDUCACION MEDIA SUPERIOR FOR. T.C. “C”",
    "CAT_SIMPLE": "PROFESOR TITULAR",
    "ORD_CAT": 5800,
    "CT_AV": null
  },
  {
    "CVE": "E3064",
    "CATEGORIA": "PROFESOR TITULAR EDUCACION MEDIA SUPERIOR D.F. T.C. “C”",
    "CAT_SIMPLE": "PROFESOR TITULAR",
    "ORD_CAT": 5800,
    "CT_AV": null
  },
  {
    "CVE": "E6114",
    "CATEGORIA": "PROFESOR TITULAR \"A\" (EDUCACION SUPERIOR) 1/2 TIEMPO",
    "CAT_SIMPLE": "PROFESOR TITULAR",
    "ORD_CAT": 5800,
    "CT_AV": null
  },
  {
    "CVE": "E6116",
    "CATEGORIA": "PROFESOR TITULAR \"B\" (EDUCACION SUPERIOR) 1/2 TIEMPO",
    "CAT_SIMPLE": "PROFESOR TITULAR",
    "ORD_CAT": 5800,
    "CT_AV": null
  },
  {
    "CVE": "E6128",
    "CATEGORIA": "PROFESOR TITULAR \"A\" (EDUCACION MEDIA SUPERIOR) 1/2 TIEMPO",
    "CAT_SIMPLE": "PROFESOR TITULAR",
    "ORD_CAT": 5800,
    "CT_AV": null
  },
  {
    "CVE": "E6130",
    "CATEGORIA": "PROFESOR TITULAR \"B\" (EDUCACION MEDIA SUPERIOR) 1/2 TIEMPO",
    "CAT_SIMPLE": "PROFESOR TITULAR",
    "ORD_CAT": 5800,
    "CT_AV": null
  },
  {
    "CVE": "E6170",
    "CATEGORIA": "PROFESOR TITULAR \"C\" (EDUCACION MEDIA SUPERIOR) 1/2 TIEMPO",
    "CAT_SIMPLE": "PROFESOR TITULAR",
    "ORD_CAT": 5800,
    "CT_AV": null
  },
  {
    "CVE": "E6214",
    "CATEGORIA": "PROFESOR TITULAR \"A\" (EDUCACION SUPERIOR) 3/4 DE TIEMPO",
    "CAT_SIMPLE": "PROFESOR TITULAR",
    "ORD_CAT": 5800,
    "CT_AV": null
  },
  {
    "CVE": "E6314",
    "CATEGORIA": "PROFESOR TITULAR \"A\" (EDUCACION SUPERIOR) TIEMPO COMPLETO",
    "CAT_SIMPLE": "PROFESOR TITULAR",
    "ORD_CAT": 5800,
    "CT_AV": null
  },
  {
    "CVE": "E6316",
    "CATEGORIA": "PROFESOR TITULAR \"B\" (EDUCACION SUPERIOR) TIEMPO COMPLETO",
    "CAT_SIMPLE": "PROFESOR TITULAR",
    "ORD_CAT": 5800,
    "CT_AV": null
  },
  {
    "CVE": "E6318",
    "CATEGORIA": "PROFESOR TITULAR \"C\" (EDUCACION SUPERIOR) TIEMPO COMPLETO",
    "CAT_SIMPLE": "PROFESOR TITULAR",
    "ORD_CAT": 5800,
    "CT_AV": null
  }
];
